version: '3'

services:
  db:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb-data:/var/lib/influxdb2
  backend:
    image: backend:0.0.1-SNAPSHOT
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env_backend
  sensor:
    image: sensor:0.0.1-SNAPSHOT
    depends_on:
      - db
      - backend
    env_file:
      - .env_sensor